//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameBuilder.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DATAPSPSD {
            get {
                object obj = ResourceManager.GetObject("DATAPSPSD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DATAPSPSDCFG {
            get {
                object obj = ResourceManager.GetObject("DATAPSPSDCFG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCES00311 87AA
        ///SCES01431 6547
        ///SCES01444 BD44
        ///SCES01492 D16A
        ///SCES01493 197A
        ///SCES01494 AAA6
        ///SCES01495 0E57
        ///SCES01516 44F6
        ///SCES01517 AE85
        ///SCES01518 9C27
        ///SCES01519 364B
        ///SCES01564 CEC1
        ///SCES01695 89EA
        ///SCES01700 4717
        ///SCES01701 C49E
        ///SCES01702 672A
        ///SCES01703 883F
        ///SCES01704 CE32
        ///SCES01763 096F
        ///SCES01882 B364
        ///SCES01909 E788
        ///SCES01979 0D9D
        ///SCES02004 C437
        ///SCES02005 9137
        ///SCES02006 7554
        ///SCES02007 E686
        ///SCES02028 9AD4
        ///SCES02029 26B6
        ///SCES02030 23D9
        ///SCES02031 D325
        ///SCES02080 9DE0
        ///SCES02104 744B
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MAGICWORDS {
            get {
                return ResourceManager.GetString("MAGICWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SIMPLE {
            get {
                object obj = ResourceManager.GetObject("SIMPLE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] STARTDATMINIS {
            get {
                object obj = ResourceManager.GetObject("STARTDATMINIS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] STARTDATPOPS {
            get {
                object obj = ResourceManager.GetObject("STARTDATPOPS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] STARTDATPSP {
            get {
                object obj = ResourceManager.GetObject("STARTDATPSP", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
