name: build

on:
  push:
    branches: [ master ]

jobs:
  build-apps:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.0.x
        include-prerelease: false
        
    - name: Restore dependencies
      run: |
        dotnet restore ChovySign-GUI
        dotnet restore ChovySign-CLI
        dotnet restore PbpResign

    - name: Build windows
      continue-on-error: false
      run: |
        dotnet publish -p:PublishProfile=Win64 ChovySign-GUI
        dotnet publish -p:PublishProfile=Win64 ChovySign-CLI
        dotnet publish -p:PublishProfile=Win64 PbpResign
        
    - name: Upload windows gui
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign2-GUI-Windows-x64
        path: ChovySign-GUI/bin/publish/windows

    - name: Upload windows cli
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign2-CLI-Windows-x64
        path: ChovySign-CLI/bin/publish/windows

    - name: Upload windows PbpResign
      uses: actions/upload-artifact@v4
      with:
        name: PbpResign-Windows-x64
        path: PbpResign/bin/publish/windows


    - name: Build linux
      continue-on-error: false
      run: |
        dotnet publish -p:PublishProfile=Linux64 ChovySign-GUI
        dotnet publish -p:PublishProfile=Linux64 ChovySign-CLI
        dotnet publish -p:PublishProfile=Linux64 PbpResign

    - name: Build linux flatpak
      continue-on-error: false
      run: |
        flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        flatpak install -y org.flatpak.Builder
        cd Flatpak-data
        ./quickpak build bundle
        cd ..

    - name: Upload linux gui flatpak
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign2-GUI-Linux-x64-Flatpak
        path: Flatpak-data/codes.silica.chovysign.flatpak

    - name: Upload linux gui
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign2-GUI-Linux-x64
        path: ChovySign-GUI/bin/publish/linux

    - name: Upload linux cli
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign2-CLI-Linux-x64
        path: ChovySign-CLI/bin/publish/linux

    - name: Upload linux PbpResign
      uses: actions/upload-artifact@v4
      with:
        name: PbpResign-Linux-x64
        path: PbpResign/bin/publish/linux
