name: build

on:
  push:
    branches: [ master ]
    

jobs:
  build-apps:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
        include-prerelease: false

    - name: Build windows
      continue-on-error: false
      run: |
        dotnet publish -p:PublishProfile=Win64 ChovySign-CLI --output bin/Windows/ChovyCLI
        dotnet publish -p:PublishProfile=Win64 ChovySign-GUI --output bin/Windows/ChovyGUI
        dotnet publish -p:PublishProfile=Win64 PbpResign  --output bin/Windows/PbpResign
    
    - name: Upload windows cli
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign-CLI-Windows-x64
        path: bin/Windows/ChovyCLI
        
    - name: Upload windows gui
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign-GUI-Windows-x64
        path: bin/Windows/ChovyGUI


    - name: Upload windows PbpResign
      uses: actions/upload-artifact@v4
      with:
        name: PbpResign-Windows-x64
        path: bin/Windows/PbpResign


    - name: Build linux
      continue-on-error: false
      run: |
        dotnet publish -p:PublishProfile=Linux64 ChovySign-CLI --output bin/Linux/ChovyCLI
        dotnet publish -p:PublishProfile=Linux64 ChovySign-GUI --output bin/Linux/ChovyGUI
        dotnet publish -p:PublishProfile=Linux64 PbpResign --output bin/Linux/PbpResign

    - name: Upload linux cli
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign-CLI-Linux-x64
        path: bin/Linux/ChovyCLI
        
    - name: Upload linux gui
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign-GUI-Linux-x64
        path: bin/Linux/ChovyGUI

    - name: Upload linux PbpResign
      uses: actions/upload-artifact@v4
      with:
        name: PbpResign-Linux-x64
        path: bin/Linux/PbpResign
