name: build

on:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.0.x
        include-prerelease: false
        
    - name: Restore dependencies
      run: |
        dotnet restore ChovySign-GUI
        dotnet restore ChovySign-CLI
        dotnet restore PbpResign

    - name: Build windows
      continue-on-error: false
      run: |
        dotnet publish -p:PublishProfile=Win64 ChovySign-GUI
        dotnet publish -p:PublishProfile=Win64 ChovySign-CLI
        dotnet publish -p:PublishProfile=Win64 PbpResign
        
    - name: Upload windows gui
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign2-GUI-Windows-x86_64
        path: build/publish/ChovySign-GUI/windows

    - name: Upload windows cli
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign2-CLI-Windows-x86_64
        path: build/publish/ChovySign-CLI/windows

    - name: Upload windows PbpResign
      uses: actions/upload-artifact@v4
      with:
        name: PbpResign-Windows-x86_64
        path: build/publish/PbpResign/windows
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.0.x
        include-prerelease: false
        
    - name: Restore dependencies
      run: |
        dotnet restore ChovySign-GUI
        dotnet restore ChovySign-CLI
        dotnet restore PbpResign

    - name: Build mac
      continue-on-error: false
      run: |
        dotnet publish -p:PublishProfile=MacARM64 ChovySign-GUI
        dotnet publish -p:PublishProfile=MacARM64 ChovySign-CLI
        dotnet publish -p:PublishProfile=MacARM64 PbpResign
        
        dotnet publish -p:PublishProfile=Mac64 ChovySign-GUI
        dotnet publish -p:PublishProfile=Mac64 ChovySign-CLI
        dotnet publish -p:PublishProfile=Mac64 PbpResign
        
# ARM Mac
    - name: Upload mac gui
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign2-GUI-Mac-ARM64
        path: build/publish/ChovySign-GUI/mac

    - name: Upload mac cli
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign2-CLI-Mac-ARM64
        path: build/publish/ChovySign-CLI/mac

    - name: Upload mac PbpResign
      uses: actions/upload-artifact@v4
      with:
        name: PbpResign-Mac-ARM64
        path: build/publish/PbpResign/mac
        
# Intel Mac
    - name: Upload intel mac gui
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign2-GUI-Mac-x86_64
        path: build/publish/ChovySign-GUI/mac-x64

    - name: Upload intel mac cli
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign2-CLI-Mac-x86_64
        path: build/publish/ChovySign-CLI/mac-x64

    - name: Upload intel mac PbpResign
      uses: actions/upload-artifact@v4
      with:
        name: PbpResign-Mac-x86_64
        path: build/publish/PbpResign/mac-x64
        
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.0.x
        include-prerelease: false
        
    - name: Restore dependencies
      run: |
        dotnet restore ChovySign-GUI
        dotnet restore ChovySign-CLI
        dotnet restore PbpResign


    - name: Build linux
      continue-on-error: false
      run: |
        dotnet publish -p:PublishProfile=Linux64 ChovySign-GUI
        dotnet publish -p:PublishProfile=Linux64 ChovySign-CLI
        dotnet publish -p:PublishProfile=Linux64 PbpResign


    - name: Upload linux gui
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign2-GUI-Linux-x86_64
        path: build/publish/ChovySign-GUI/linux

    - name: Upload linux cli
      uses: actions/upload-artifact@v4
      with:
        name: ChovySign2-CLI-Linux-x86_64
        path: build/publish/ChovySign-CLI/linux

    - name: Upload linux PbpResign
      uses: actions/upload-artifact@v4
      with:
        name: PbpResign-Linux-x86_64
        path: build/publish/PbpResign/linux

  build-flatpak:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: ChovySign2-GUI-Linux.flatpak
        manifest-path: Flatpak-data/codes.silica.chovysign.yml
        cache-key: flatpak-builder-${{ github.sha }}
        upload-artifact: true
